version: '1.2'

services: 
  postgres_data: 
    image: postgres:15
    healthcheck:
      test: ["CMD","pg_isready", "-q", "-d","jdea_lab", "-U"]
      interval: 10s
      timeout: 45s
      retries: 5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jdea_lab
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
    - /tmp/database:/var/lib/jdea_lab/data
    ports: 
    - 5432:5432



